### PR TITLE
Descriptive errors. Fixes #13

### LINKED ISSUE #13: Error reporting is overly broad
https://github.com/mapbox/shapefile-fairy/blob/master/index.js#L19-L20

This code checks for the existence of shp, dbf, and shx files and returns an error that says:

> Failed to find a shapefile in your zip

This refers to shapefile as a singular and doesn't help the user to understand the requirements or which files are missing.

### PR DESCRIPTION
**Pull request by tmcw**
Adds new error messages for missing and duplicate files,
and new fixtures to test for them.

cc @GretaCB for the review

cc @lyzidiamond from a helping-users-debug perspective, is this the right level of specificity?

### CODE REVIEW

**Comment by GretaCB** [comment]
@tmcw looks good in staging :+1: 

screen shot 2015-11-24 at 10 21 30 am

**Comment by GretaCB** [comment]
@tmcw I am in the process of fixing sem ver issues with tilelive in unpacker, so once I get that ready to go, I can merge/deploy this along with it.

**Comment by GretaCB** [comment]
All set to merge/deploy.

> cc @lyzidiamond from a helping-users-debug perspective, is this the right level of specificity?

@lyzidiamond, stamp of approval?

**Comment by lyzidiamond** [comment]
@GretaCB @tmcw looking at this now

**Comment by lyzidiamond** [comment]
This is much clearer. :+1: from me.

**Pull request merged**
